PR#1  UIのみ完成。挙動、未実装。
wada-mitsuki/bear-trace pull request #1
Opened 2024-01-05 06:33 UTC by wada-mitsuki

ひとまず大きな出戻りがないよう、一度下記の点で確認していただきたく、PRいたしました！
お手隙の際にご確認お願いいたします。
・ディレクトリ構造に問題はないか
・デザインの実装法に問題はないか
![スクリーンショット 2024-01-05 15 26 24](https://github.com/wada-mitsuki/bear-trace/assets/155605746/cdc2a203-f128-4bdc-9df1-64f5d078f5dc)

その後は、以下の順番で着手していきたいと思いますので、ご認識のほどお願いいたします！
・さらに小さな単位でコンポーネントにまとめたり、共通化できそうなパーツは別コンポーネントでまとめる
・検索バー表示の実装
・新規メモの追加
・メモ編集の保存
・サムネイルの表示
・マークダウン記法

2024-01-05 09:10 UTC, maemura-katsuki commented
ごめん、事前に決めておくべきやったけど、今回のコンポーネントのフォルダ構成は、sj-sfaにできるだけ寄せて以下のような感じにしましょう。

```
- components
  - shared - いくつかのコンポーネントで構成されるような、固有のページに依存しないし、複数画面で使い回せるようなコンポーネント
  - ui-parts - いくつものコンポーネントで使い回せるような、ビジネスロジックをもたない、最小単位のUIコンポーネント 
```

それに伴って、各コンポーネントをもう少し細かい粒度で分けてもらえると嬉しいです！

2024-01-05 09:11 UTC, maemura-katsuki commented
ざっとみのUI、ライブラリの使い方、速さ等はめっちゃいいと思います 👍

2024-01-05 09:11 UTC, wada-mitsuki commented
以下のコミットでディレクトリ構成を見直してます。
c91ccc6516662d04b0733a6668c7e5f7f227ffef

2024-01-05 09:42 UTC, wada-mitsuki commented
```
- components
  - shared - いくつかのコンポーネントで構成されるような、固有のページに依存しないし、複数画面で使い回せるようなコンポーネント
  - ui-parts - いくつものコンポーネントで使い回せるような、ビジネスロジックをもたない、最小単位のUIコンポーネント 
```

ご指摘いただいたディレクトリ構成に修正いたしました！
03106f269f5d2927ba3db25d2a026838be6790fc

ですが現時点で`ui-parts`配下になりうるコンポーネントがないかな？と思ったので、`ui-parts`はなしにしてます！
今後出てきたら作成するようにします！

2024-01-09 05:42 UTC, maemura-katsuki requested changes
コメントしました！

2024-01-09 05:42 UTC, maemura-katsuki commented on tailwind.config.js
> +    './components/**/*.{js,ts,jsx,tsx,mdx}',
これ調べて新しく設定追加したのナイス👍  
でもフォルダの場所としては、 `src` の配下に `components` を置く方が多いかも🥲  

現場でよく使われるフォルダ配置としては、以下になるのが多いです。　　
プロジェクトのルートディレクトリ以下に設定ファイルとか基盤関係のもの、  
`src` の下にアプリケーションに関わるプログラムファイル

2024-01-09 05:42 UTC, maemura-katsuki commented on components/shared/contents/Contents.tsx
> +      <main className="mt-20 mx-14">
ここの余白の取り方はマージンではなくパディングのほうがいいかも。  
パーツとパーツの距離を取るのはマージン、パーツ内の余白を作るのはパディングっていう認識です！

2024-01-09 05:42 UTC, maemura-katsuki commented on components/shared/contents/ContentsHeader.tsx
> +    <Header className="top-0 right-0 bg-white border-b-2 fixed top-0 left-80 min-w-96">
ダブってない？👀

2024-01-09 05:42 UTC, maemura-katsuki commented on components/shared/contents/ContentsHeader.tsx
> +        </Flex>
ここの距離のとり方 `margin` じゃなくて `gap` 使えへんかな？

2024-01-09 05:42 UTC, maemura-katsuki commented on components/shared/contents/ContentsHeader.tsx
> +        <Flex gap="small">
この `Flex` っているやつ？🤔

2024-01-09 05:42 UTC, maemura-katsuki commented on components/shared/sidebar/SideBarHeader.tsx
> +          prefix={<SearchOutlined className="site-form-item-icon" />}
この `site-form-item-icon` っているやつ？

2024-01-09 05:42 UTC, maemura-katsuki commented on components/shared/sidebar/SideBarContents.tsx
> +            <p className="">落ち着いて、何か書いてみましょう</p>
👀

2024-01-09 05:43 UTC, merged