Pr#4 メモ編集機能
wada-mitsuki/bear-trace pull request #4
Opened 2024-01-11 02:09 UTC by wada-mitsuki

メモの編集機能を追加しました。
まだマークダウンには対応していないので、一旦`Input`,`TextArea`で対応しています。
この後マークダウン対応します。

以下が挙動概要です
・Side Barのクリップを選択すると選択されたクリップが`stateのselectedClip`に保存される
・content部分は、`selectedClip`が表示される
・フォーカスアウトすると、内容が更新される

<img width="929" alt="スクリーンショット 2024-01-11 11 06 05" src="https://github.com/wada-mitsuki/bear-trace/assets/155605746/c6c16420-8492-486d-a579-96f43bd69819">

2024-01-11 03:06 UTC, maemura-katsuki requested changes
いくつかコメントしました！

2024-01-11 03:06 UTC, maemura-katsuki commented on src/store/clip.state.ts
> +  selectedClip: Clip;
現在選んでるclipは、clipそのものじゃなくてidで管理するほうが一般的かも

2024-01-11 03:06 UTC, maemura-katsuki commented on src/components/shared/sidebar/hooks/useSideBarContents.tsx
> +    console.log(clip);
👀

2024-01-11 03:06 UTC, maemura-katsuki commented on src/components/shared/sidebar/hooks/useSideBarContents.tsx
> +    dispatch(clipActions.selectedClip(clip));
`page` ディレクトリ追加したから、storeの更新処理とかはそっちでやりたいな。  
`shared` データに依存する分 `UI` より持てる責任(コンポーネントでやっていい処理)が多くて、例えば画面表示のためのデータ取得とかは `shared` コンポーネントがやってもいいんやけど、  
storeの更新は、 `page` の方の責任にしたい。  
なんでかというと、 `store` は今回の想定してるreduxの使い方でいくとデータに依存するんじゃなくて、画面に依存するからです。  
すまん！抽象的な説明しかできないんで、分かりづらいと思うけど、今はニュアンス拾ってもらえれば！

2024-01-11 03:06 UTC, maemura-katsuki commented on src/components/shared/contents/hooks/useContentBody.tsx
> +
ここって `useState` の初期値に設定するのでは想定した動きにならなかったから `useEffect` ？

2024-01-11 03:06 UTC, maemura-katsuki commented on src/components/shared/contents/ContentBody.tsx
> +    <main className="mt-20 mx-12" onBlur={onSaveText}>
bear見ると、storeへの反映はonBlurの他にデバウンスでも反映されてそうやから、その処理も追加お願いします！

2024-01-11 03:06 UTC, maemura-katsuki requested changes
いくつかコメントしました！

2024-01-11 03:41 UTC, kamakura-hideki requested changes

2024-01-11 03:41 UTC, kamakura-hideki commented on src/components/shared/contents/hooks/useContentBody.tsx
> +    };
@wada-mitsuki 
bearは更新日時が現在との相対日時を表記しているようなので、時間まで持っておいた方が良さそうですね！
toLocaleDateString だと保存した時間が省略されているので、 toLocaleDateString はなくて良いかもしれません   👀

2024-01-11 03:42 UTC, kamakura-hideki commented
@wada-mitsuki 
1点コメントしました！

2024-01-11 05:05 UTC, wada-mitsuki commented on src/components/shared/sidebar/hooks/useSideBarContents.tsx
> +    dispatch(clipActions.selectedClip(clip));
すみません、ここ完全に理解できていないので明日の朝会時で構いませんので、教えていただきたいです🙇
今はpageのhooksを作成してそこで全てのstoreの更新処理を管理したいと思います :eye:

2024-01-11 07:11 UTC, wada-mitsuki commented on src/components/shared/contents/hooks/useContentBody.tsx
> +    };
@kamakura-hideki 
ごもっともです。。。
日付フォーマットを修正して色んな箇所で使うかなとお思ったのでutils配下に現在時刻を取得するutil関数を作成しました！
以下のコミットで修正しています！
fdb58c2d232608fed4b1f11beeabc4216f76b0a2

2024-01-11 07:11 UTC, wada-mitsuki commented on src/components/shared/contents/ContentBody.tsx
> +    <main className="mt-20 mx-12" onBlur={onSaveText}>
デバウンス処理実装しました！
4b4345695c28e689fdbab18bbd6bfe1bcf75d29a

2024-01-11 07:11 UTC, wada-mitsuki commented on src/components/shared/contents/hooks/useContentBody.tsx
> +
初期値に設定してもclipが切り替わると反映されなかったので
useEffectでclipを監視するようにしました :eyes:

2024-01-11 07:11 UTC, wada-mitsuki commented on src/components/shared/sidebar/hooks/useSideBarContents.tsx
> +    dispatch(clipActions.selectedClip(clip));
イメージ通りか自信がないですが,storeの更新処理はpageで行うように修正してみました！
修正に伴い、必要のないファイルも削除してます！

以下コミットで修正してます！
56936b212d3f352d5b7c563373a804b186b3e158

2024-01-11 07:11 UTC, wada-mitsuki commented on src/components/shared/sidebar/hooks/useSideBarContents.tsx
> +    console.log(clip);
本当にすみません。。。削除してます。。。

2024-01-11 07:11 UTC, wada-mitsuki commented on src/store/clip.state.ts
> +  selectedClip: Clip;
idで管理するように修正しました！
他コミット（56936b212d3f352d5b7c563373a804b186b3e158）で影響はあると思いますが以下のコミットで修正してます！
9a912d880c2be21ae2ca3e891b8e33c050119459

2024-01-11 10:12 UTC, maemura-katsuki commented on src/components/shared/contents/hooks/useContentBody.tsx
> +
納得です！

2024-01-11 10:16 UTC, maemura-katsuki commented on src/store/clip.state.ts
> +  selectedClip: Clip;
iine!

2024-01-11 10:30 UTC, maemura-katsuki reviewed
pageへの引き上げ、こんな感じやと思います！
いくつか追加でコメントしました！

2024-01-11 10:30 UTC, maemura-katsuki commented on src/components/shared/contents/Contents.tsx
> +  const { selectedClip } = useContents();
`selectedClip` も外からpropsで渡してやってもいいかも！  
副業のform系のコンポーネントって、 `value` と `onChange` はproprsで受け取って、画面表示と操作だけ担当するようにしてたと思うんやけど、  
あれとおんなじイメージで！

2024-01-11 10:30 UTC, maemura-katsuki commented on src/components/shared/sidebar/SideBar.tsx
> +  const { clips } = useSideBar();
ここも同じく、pageから受け取っていいと思います！

2024-01-12 01:21 UTC, wada-mitsuki commented on src/components/shared/sidebar/SideBar.tsx
> +  const { clips } = useSideBar();
clipsもpageへ引き上げました！

以下のコミットで修正しました！
797cced6213a2932efdb016691871ac33405155f

2024-01-12 01:21 UTC, wada-mitsuki commented on src/components/shared/contents/Contents.tsx
> +  const { selectedClip } = useContents();
あぁ〜〜〜〜 🤔 
徐々にわかってきました。。。具体的な業務のデータなどはpageが責任もつってことですかね。
selectedClipもpageへ引き上げました！

以下のコミットで修正しました！
797cced6213a2932efdb016691871ac33405155f

2024-01-12 01:42 UTC, kamakura-hideki approved these changes

2024-01-12 04:32 UTC, maemura-katsuki approved these changes
いいと思います！ 👍 
![LGTM](https://image.lgtmoon.dev/233352)

2024-01-12 07:19 UTC, merged